language: python
puthon: 3.8
script:
echo Starting work...
branches:
  only:
  - master
  - dev
import:
- source: .travis/masterTest.yml
  if: branch = master
- source: .travis/devTest.yml
  if: branch = dev
